######################################################################
# Automatically generated by qmake (3.0) ??? ?? 15 13:19:03 2016
######################################################################

TEMPLATE = app
TARGET = ihouqin
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += pushbutton.h ihouqinwindow.h
SOURCES += pushbutton.cpp ihouqinwindow.cpp main.cpp
RC_ICONS = resources/ihouqin.ico
TRANSLATIONS = ihouqintr_chn.ts
